### PR TITLE
added scrapper for haircut-practice

### PR DESCRIPTION
**Pull request by scharlau**
I worked out how to get everything running with node and yarn, which is new to me, and then found that when running the bin scraper generate command I was able to create the correct rss page for haircut-practice with the scrapper I created. 

Thanks for making this possible. I'll see if I can do a few more of these scrappers to make it easier to see comics in rss. So much less hassle than going to every website.

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Hey, sorry I've been out of contact on this PR and on the email. When I get some time I'll take a look, which will hopefully be tomorrow.

**Comment by scharlau** [comment]
It’s fine. I got it sorted. Sent a pull request to github, which must’ve pulled the code as it was available on the rss feed the next day.

I’ll see about addressing some of the other feed requests too when I have time. This is a good way for me to better understand javascript and then node applications too.


--
cheers,

Bruce

Dr. Bruce Scharlau
Dept. of Computing Science
Meston Building, Room 225
University of Aberdeen
Aberdeen AB24 3UE
01224 272193
http://homepages.abdn.ac.uk/b.scharlau/pages/
http://twitter.com/scharlau
mailto:b.scharlau@abdn.ac.uk

**Comment by scharlau** [comment]
I've been working on the Arcamax scrapper and discovered that this code is broken. I thought it was working fine, but see now that it seemed to work as it's on Go Comics and covered by that scrapper via the a->z. I'll hopefully have a working version before too long. Sorry for the mistake.

**Comment by ArtskydJ** [comment]
Hey @scharlau, thanks for your effort nonetheless. I'll close this PR.

If you are currently working on an Arcamax scraper, let me know! (Feel free to use what I started in `_generator/scrapers/wip-arcamax`. I don't really have any code started, but I've got a couple HTML files that I scraped from the arcamax website a while back.)

**Pull request closed without merging**
