### PR TITLE
revamped frontend

### LINKED ISSUE #136: Display a better icon for the Source
image

I want to switch out
image
with
 [Source](https://www.arcamax.com)
and
 [Source](https://comicskingdom.com)
etc.

### LINKED ISSUE #138: improve frontend
frontend appearence of the project can be improved. Please assign me under hactoberfest if you want.

### PR DESCRIPTION
**Pull request by itsjustneo-xo**
# Fixes #138 
# Fixes #136 

# Changes Implemented
- Removed label 'Search'
- Added placeholder 'Filter Comics'
- Added space between list and search input
- Changed bg-color
- Change bg-color for Contact section
- Changed icon for 'Source'
- Removed 'Contact' from nav

# Preview 

image

image

### CODE REVIEW

**Comment by ArtskydJ** [comment]
I'm not sure I love the light orange background, but I'll see if it grows on me.

**Comment by itsjustneo-xo** [comment]
Just noticed that most of the changes I've made aren't applied due to the most recent commit reverting them

**Comment by ArtskydJ** [comment]
This is what I'm seeing on comicsrss.com:

image

**Comment by itsjustneo-xo** [comment]
Yes, from the changes mentioned in the PR, the following have been overwritten by the recent commit (which were added in the PR) - 

- Removed label 'Search'
- Added placeholder 'Filter Comics'
- Added space between list and search input
- Changed icon for 'Source'
- Removed 'Contact' from nav


The commit after merging this PR overwrites these changes to the old code

**Comment by ArtskydJ** [comment]
Oh, sorry, I see what happened.

`index.html` and `espanol.html` are generated from these files:
https://github.com/ArtskydJ/comicsrss.com/tree/gh-pages/_generator/site-generator/template

I totally missed that you hadn't changed any of those template files.  So the CSS changes stuck around, but not the HTML changes.

**Comment by itsjustneo-xo** [comment]
> Oh, sorry, I see what happened.
> 
> `index.html` and `espanol.html` are generated from these files: https://github.com/ArtskydJ/comicsrss.com/tree/gh-pages/_generator/site-generator/template
> 
> I totally missed that you hadn't changed any of those template files. So the CSS changes stuck around, but not the HTML changes.

Oh. My bad. Do you want me to change the template files?

**Comment by ArtskydJ** [comment]
I re-added your changes to the templates.

**Pull request merged**
