### PR TITLE
📅 Recent Changes

### PR DESCRIPTION
**Pull request by ayush-pandey047**
I have updated your readme.md in very user-friendly. I added emoji and comprise the big content into small read easily.

### CODE REVIEW

**Comment by ayush-pandey047** [comment]
plz don't make this spam. I just want to make it good if you don't want just leave this. I am beginner in this field so plz  don't do this.

**Comment by ArtskydJ** [comment]
I added the spam tag because I thought it looked like you used an LLM to modify the readme, and were doing that for multiple repos.  (And your account is a few days old.)

I don't actually know if you're using an LLM and not verifying the output, so I'll remove the tag.

**Comment by ArtskydJ** [comment]
Sorry if you did put a bunch of effort into this.  I think the PR had some improvements.  It also just isn't written in my voice.

**Comment by ayush-pandey047** [comment]
If you like my work so pull it  and merge it, otherwise thank you for removing spam. Actually I am a first year college student and we got a target to get more than 10 pull or accept 4 pull. That's why this is a new account.

**Pull request closed without merging**
